### ISSUE TITLE
send to reviewers for marking conficts?

### ISSUE THREAD

**Issue by timm** [researchart/icsme16#10]
@obaysal : are we still chasing late authors for icsme artifacts? i've got our four titles in http://tiny.cc/icsme16art. should i send these to reviewers for their conflict lists? or wait N more days (N being a small number)

**Comment by obaysal** [comment]
@timm let's give another day before we send an email to reviewers.

**Comment by timm** [comment]
ok. leave it to you. ping me when you think we have all that we will have. then i will
- update the master spreadsheet
- ping our reviewers re conflicts etc

t

**Comment by grammarware** [comment]
_(I hope you don't mind me barging into your conversation. That's what you get for making it public)_

We also have a [dataset](http://leonardpunt.github.io/masterproject/dataset-and-results.zip) that we might submit since it can be used without our tool as well. However, @leonardpunt wants to do a proper write-up for  which he will have time on Sunday. Should we do that? I can also submit a draft today so that the bidding can start, and update it the day after tomorrow with the proper PDF. It's already been online for almost a year so we don't mind any other way, just wanted to bump up the numbers for the track to succeed. Please advise. Thanks!

**Comment by obaysal** [comment]
@grammarware I think it would be good if you could submit a draft for reviewers' bidding. You can update the paper on Sunday then. I am fine with this. @timm what are your thoughts on this?

**Comment by obaysal** [comment]
@timm master sheet is final unless @grammarware submits another artifact. No other pending submissions.

**Comment by obaysal** [comment]
@timm why is submission#5 marked as withdrawn? my understanding is submission#5 is complete, while submission#7 is a draft for now until Sunday. did i missed anything?

**Comment by grammarware** [comment]
I put both in one directory, was that the reason?

**Comment by obaysal** [comment]
@grammarware all is fine, I fixed it.
