### ISSUE TITLE
Pinto_ThreadSafeDataStructures

### ISSUE THREAD

**Issue by gustavopinto** [researchart/icsme16#12]

**Comment by mvdbrand** [comment]
The artefact description briefly describes the purpose and goal of the artefact. The artefact 
measures the energy consumption of multi-threaded Java code. The description clearly describe
the insightful, useful and usable aspects of the artefact. The motivation of cost-effectiveness is 
"strange" because one would expect a motivation on the (implementation) effort for monitoring
the Java code. 

The description of the artefact does not contain an installation guide. The Dropbox line in the 
Section C (Summary) does not work. The Github link does not lead to an installation guide, there
a concise README can be found. The Section IV (Organization and Utilization) contains a
description of the folder structure.

I would classify this artefact as ? accept.

**Comment by gustavopinto** [comment]
Hi, thanks for reviewing this artifact. 

Just for clarification, we did not provide any installation guide because we did not propose any new tool. Instead, we use an existing tool to measure energy consumption. Since this tool has its own installation guide, we decide to not duplicate it in the artifact. 

As regarding the dropbox link, this is the correct one: https://www.dropbox.com/sh/1o0twfnfenvgk7m/AAAs35TcpfAMQsX2a8eOyZ8Ja?dl=0. I'll be happy to update the link in the paper, if accepted.

**Comment by agurfinkel** [comment]
The artifact consists of a package to reproduce the experiments and
analysis of the corresponding paper. The scorecard describes the
content of the artifact and guidelines on reproducing the experiments.

The artifact itself is available from Dropbox. Contrary to the
scorecard, I could not find README files that describe what to do with
the artifact. Everything to reproduce the results seems to be
included. However, I could not reproduce the experiments during the
review cycle due to the complexity of the installation procedure (I
would have appreciated an easy-to-reproduce environment such as
VirtualBox or Docker).

Overall, the artifact meets the expectations and I recommend
acceptance.

**Comment by agurfinkel** [comment]
re-opening until all reviews come in.

**Comment by emhill** [comment]
I like the idea behind this artifact, of energy efficiency benchmarks. I would have appreciated a better explanation of how to run the artifact, and an easier way to access it. I couldn't download the top level folder from dropbox's website (I got an error), but was able to download each of the 3 folders underneath that level.

Specific commands to run the artifact,  that could be typed at a _nix prompt, would have been appreciated. I had some trouble running the artifact. The authors don't state *why_ java 7 is needed, and the run.sh script in the microbenchmark used java7 (I assume to avoid conflicts with later versions). When I tried to run it, I got the following error:

```
Error occurred during initialization of VM
Too small initial heap

```

This may have also been due to the fact that I was using java 8 OR that I didn't install jRAPL. Making the instructions fool proof in a numbered list would definitely help smooth this process.

I was able to access the images in the other sections fine.

**Comment by emhill** [comment]
Looking at the author's prior comment, a link to the external tool's install guide would have sufficed in the text. I'm glad they chose not to duplicate it!

The problem is that the requirements & instructions for running the artifact are missing, and it's not obvious how it should be executed/evaluated.

**Comment by gustavopinto** [comment]
Hi @emhill, thanks for raising these issues.
- The artifacts are now in a zip file. So there might be easier to download the files.
- We need Java7 because the experiments were conducted with Java7. No other restriction.
- The error received can be solved with an additional JVM flag (-Xmx2048m). I didn't mentioned that in the artifact because this error wasn't known. 
- To execute the artifact, one just need to run the programs available at the dropbox folder with the jRAPL tool. This tool only works with Intel CPUs, and might have some other unknown limitations (not sure how we can handle this since we are not the main authors of this tool). If you want to evaluate the artifact, you can plot the plot data (.csv files) and compare with the ones presented in the paper. 

If accepted, I will fix all these problems in the artifact.

**Comment by obaysal** [comment]
@agurfinkel and @mvdbrand suggested "accept", while @emhill had some troubles running the tool. @timm what do you think?

**Comment by timm** [comment]
@obaysal : I'm going to say accept and I'm going to require @gustavopinto  make the changes he mentions in his last comment.
