### ISSUE TITLE
Zaytsev_data

### ISSUE THREAD

**Issue by grammarware** [researchart/icsme16#13]

**Comment by ctreude** [comment]
This artifact is well motivated. As the authors state, replicating website analysis papers is next to impossible since web applications are continuously being changed. Providing snapshots of popular websites along with the results of a CSS analysis makes perfect sense and is useful to the community.

The artifact is well structured. The directory structure is intuitive, and all the information appears to be where a user would expect it. After reading the pdf, I was expecting that the artifact would contain the analysis tool as well, but that doesn't appear to be the case. The sentence "Providing both the dataset and the tool allows to easily retarget them for the next target" is a bit misleading in this context. I'm wondering if there's a particular reason for the tool not to be included in the artifact? It would be nice to be able to re-run the analysis on the snapshots and possibly compare the results with those for more recent snapshots.

I'm happy to recommend acceptance of this artifact at ICSME. I also appreciate the amount of detail that the authors provide regarding the issues they had with the dataset.

**Comment by grammarware** [comment]
2 @ctreude: we meant #11 with that sentence. If accepted, will rewrite to make the intent more apparent. Thank you!

**Comment by mcmillco** [comment]
Very Brief Summary

The artifact is a dataset for evaluating CSS at large organizations, focused on refactoring and "undoing style."

Insightful

The paper makes a good point that websites change so often, that it is almost impossible to reproduce research on those websites.  This artifact solves that problem by providing a consistent dataset based on existing research papers.

Useful

The dataset makes it possible to have a consistent dataset for benchmarking research results.  Also, the dataset provides a record of CSS at websites for 40 large organizations from 2015.  If a researcher wants to do a comparative analysis over a number of years, this dataset may be the researcher's only choice.

Usable

I found the dataset to be easy to access and understand.  All I had to do was download the zip file and navigate to the folder for the organization I wanted to view.

This dataset should be included in the artifacts track.  Datasets of this type are hard to come by, and future researchers will benefit by having it available as a "time capsule" of CSS at large organizations at a specific time.

**Comment by emhill** [comment]
In this work, the authors have created a dataset of web applications and the results of applying a CSS unrolling. This seems like a highly useful dataset for future replications. I particularly liked how the authors described some of the issues with the dataset, openly shared ambiguities in the prior work they were trying to replicate, and detailing how the issues were handled. The artifacts were straightforward to access.

Although outside of the current scope, it would be interesting if this dataset could be expanded in future to include additional information that might be appropriate to other studies, such as usage or other dynamic data.

I am happy to recommend that this be accepted.

**Comment by obaysal** [comment]
It seems that all reviews support the acceptance of this artifact.
