### ISSUE TITLE
Rahimi_Cassandra

### ISSUE THREAD

**Issue by MonaRahimi** [researchart/icsme16#9]

**Comment by hongyujohn** [comment]
Brief Summary
This artifact contains a dataset on evolution of trace links:
1.  Cassandra source code across 27 versions;
2.  Feature descriptions over all these versions;
3.  Trace Matrices for starting and ending version.
This dataset is useful. However, the tool/method that collects these data is not provided. 

Insightful
Software traceability is an important topic, which supports many software engineering activities such as impact analysis and coverage analysis. This dataset could be used to facilitate research on traceability. 

Useful
This data provides multiple versions of requirements, source code, and trace matrices (start & end version). Each matrix includes trace links between the 48 feature descriptions. Collecting such data is not easy. If this dataset is released publicly, it should be useful.

Usable
Data is stored in a standard format that can be easily parsed. It also comes with a detailed explanation. The standard format of the data and the instructions make this dataset usable.

**Comment by brusso123** [comment]
Dear authors, 

the artefact is a dataset of various versions of Apache Cassandra Distributes system. The dataset includes the description of the features of all versions considered in the paper and two link matrices between features and code files for the initial and final version. 

As the goal of the authors is to provide a dataset for software traceability I would have expected to see the link matrix for all the versions. 
The method to get the features and link matrix is mainly manual and therefore hard to verify, reproduce or extend. Mining the Jira repository of Cassandra could provide features and their description in an automatic way for example. 

I see this artefact as an initial initiative that has some good potential but only partially exploitable as is. ? reject

Barbara

**Comment by JaneClelandHuang** [comment]
Barbara,

I am responding as one of the co-authors..

While we agree with you that we would ideally have trace links for all intermediate versions - and that such a dataset would be an excellent community resource we would like to point out a couple of factors that make it of value as-is:

Each of our beginning and ending versions have Source Code (in several representations), Features (extracted from Release documents), and Trace matrices.  Constructing this for even two versions is _very_ time consuming. While it is of course ideal to have the trace matrices for all versions - waiting for this to happen inhibits research.  Our ICSE-FOSE paper (based on community input) specifically called out the problem that traceability researchers focus almost entirely on generating trace links from scratch and ignore the problem of evolving links because there are no community datasets for supporting this research.  The datasets as available today -- allow a researcher to evaluate trace link evolution algorithms across a substantial series of changes and measure the resulting accuracy.    The dataset as it stands would enable a new research focus on trace link maintenance.

The traceability community has a practice of sharing datasets which are then evaluated and improved (if necessary) by the community.  We have, to the best of our ability, evaluated the trace links - in most cases through references in the released documentation.  However, by releasing the artifacts - we encourage community feedback.

Our dataset is not "yet another" dataset in a well populated area.  It is a serious initial attempt to put data into the public domain to encourage research.  If released publicly, we anticipate further community involvement.  Reviewers of our ICSME paper have specifically stated that they are keen for the data to be made publicly available.  So we do agree with you that this dataset is an initial initiative -- however, it is a useful initial initiative which can be of value to researchers today.

We therefore hope you reconsider your 'reject' recommendation.

Thanks,

Jane

**Comment by Felienne** [comment]
I think this is an interesting dataset, that will indeed allow other researchers to build upon. As @hongyujohn says, gathering and classifying such data is not easy. As such I would argue for inclusion.

But important information on how the data was collected is indeed missing. Suppose researchers want to extend  the data with another system? How would they go about that? To make the artefacts really useful, this information has to be added.

**Comment by JaneClelandHuang** [comment]
We would certainly be willing to describe the process in more detail.  We could add a new process document as part of the artifact.  This would describe  the process we followed to construct the artifact. We could also summarize the process and reference the document in the Artifact paper.

**Comment by timm** [comment]
@hongyujohn and @Felienne . please comment on your recommendation: "?maybe accept" or "?maybe reject"

**Comment by hongyujohn** [comment]
I am ok with a "?maybe accept" if the authors can clearly describe the process they followed to construct the artifact...

**Comment by brusso123** [comment]
Hi,
I am sorry, but I still have concerns on this artefact. My point is not at all about "yet another" dataset  as I clearly see the effort the authors have done.  I do agree that manually linking features to code is a long straightforward work, but using some repositories features (like Jira features) and/or text mining techniques would help automatise and shorten the work considerably and make the overall procedure clearer and replicable. Thus, the choice to use a manual approach to create the links (which I see the most valuable piece of work in the whole artefact) is an authors' one. 

In addition, the manual work that the authors did for creating the links must be explained and verified and possibly formalised before considering the dataset as an artefact (dear authors you are waiting for the community feedback; I would wait for it before stating the dataset is an artefact). Just recalling what the call says: it must be a "reusable units of research that can be used to support other research endeavors." To reuse such an artefact, researchers must be able to replicate the whole procedure also on the same and different versions. 

Thus, the questions that tickle me are: would I use this dataset as is now? If my goal is evolutionary, would I limit my research in using two matrices only? Frankly I would not, but I do agree that this is a good initial step for a future well-packaged artefact. 

Barbara

**Comment by JaneClelandHuang** [comment]
Barbara,

We did automate the mining of issues from Jira - but we found they were too low level to meet our goals of exploring trace link evolution between requirements (aka feature descriptions) and source code.  

Thanks for considering our comments,

Jane

**Comment by timm** [comment]
@Felienne : please comment on your recommendation: "?maybe accept" or "?maybe reject". 

when doing do, please consider @JaneClelandHuang 's comments above but also please reflect on the concerns of @brusso123

**Comment by obaysal** [comment]
Reviews of @hongyujohn and @Felienne suggest that the artifact can be potentially useful. Description of the process to construct the artifact would be beneficial though. While @brusso123 raised some concerns, I believe that the dataset has a potential to study, understand and expand on the "trace link" maintenance. @timm what are your thoughts on this one?

**Comment by timm** [comment]
We need an answer today and  I'd prefer to wait till @Felienne answers my question above. But since we need a decision now, I note that:
-  while @JaneClelandHuang  makes a good response...
- we really have only one strong positive review + two with reservations.

so with that evidence, I am leaning towards ?reject. 

@obaysal : do you concur?

**Comment by JaneClelandHuang** [comment]
Tim -- we'll make this easy.  The reviewers have convinced both Mona and I that it would be better to defer release of the artifact officially.  So we agree with the reject decision (or withdraw!).  We'll try to further build up the data set and submit later.  Not wanting to annoy our ICSME research paper reviewers (who specifically requested that we make the data set publicly available) - we will also add a comment to our research paper saying that the data set is available upon request.  Hopefully everyone will be appeased - and our final data set will be really useful.  Thanks to all the reviewers.  I don't know whether you liked this open discussion - but I thought it was quite fun.

**Comment by MonaRahimi** [comment]
Dear Tim and Olga could you please let us know where you prefer us to upload the dataset. Thanks

**Comment by timm** [comment]
How big is the data? If not a gigabyte, upload to this repo

**Comment by JaneClelandHuang** [comment]
We already posted it now.  Thanks.
